# Generated by Django 5.0.6 on 2024-07-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmail', '0003_alter_email_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='title',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='email',
            name='from_email',
            field=models.EmailField(default='monuansar98@gmail.com', max_length=254),
        ),
    ]
