# Generated by Django 5.0.6 on 2024-07-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmail', '0004_rename_title_email_subject_email_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='folder',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('starred', 'Starred'), ('sent', 'Sent'), ('drafts', 'Drafts'), ('outbox', 'Outbox'), ('spam', 'Spam'), ('bin', 'Bin')], default='inbox', max_length=10),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.EmailField(max_length=254),
        ),
    ]
