# Generated by Django 5.0.6 on 2024-07-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmail', '0006_email_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
