# Generated by Django 5.0.6 on 2024-07-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmail', '0007_email_is_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='is_sent',
        ),
        migrations.AlterField(
            model_name='email',
            name='folder',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('starred', 'Starred'), ('drafts', 'Drafts'), ('outbox', 'Outbox'), ('important', 'Important'), ('bin', 'Bin')], default='inbox', max_length=10),
        ),
    ]
