# Generated by Django 5.0.6 on 2024-07-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akmail', '0008_remove_email_is_sent_alter_email_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=255)),
                ('email_port', models.PositiveIntegerField()),
                ('email_host_user', models.EmailField(max_length=254)),
                ('email_host_password', models.CharField(max_length=255)),
                ('email_use_tls', models.BooleanField(default=False)),
                ('email_use_ssl', models.BooleanField(default=False)),
            ],
        ),
    ]
