# Generated by Django 5.0.6 on 2024-07-15 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akmail', '0009_emailsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSettings',
        ),
    ]
